// Lista completa de cidades brasileiras (todas as capitais, cidades médias e grandes)
export const BRAZIL_CITIES = [
  // Acre
  'Rio Branco',
  'Cruzeiro do Sul',
  'Sena Madureira',
  'Tarauacá',
  'Feijó',
  'Brasiléia',
  'Plácido de Castro',
  'Senador Guiomard',
  'Xapuri',
  'Epitaciolândia',
  'Acrelândia',
  'Bujari',
  'Capixaba',
  'Mâncio Lima',
  'Rodrigues Alves',
  'Porto Acre',
  'Assis Brasil',
  'Marechal Thaumaturgo',
  'Jordão',
  'Santa Rosa do Purus',
  'Manoel Urbano',
  'Porto Walter',

  // Alagoas
  'Maceió',
  'Arapiraca',
  'Palmeira dos Índios',
  'Rio Largo',
  'Penedo',
  'União dos Palmares',
  'São Miguel dos Campos',
  'Santana do Ipanema',
  'Delmiro Gouveia',
  'Coruripe',
  'Marechal Deodoro',
  'Pilar',
  'Murici',
  'Arapiraca',
  'Campo Alegre',
  'Viçosa',
  'Porto Calvo',
  'São Luís do Quitunde',
  'Atalaia',
  'Matriz de Camaragibe',
  'Passo de Camaragibe',
  'Porto Real do Colégio',
  'Igreja Nova',
  'Teotônio Vilela',
  'Girau do Ponciano',
  'Messias',
  'Maribondo',
  'Traipu',
  'Belém',
  'Cajueiro',
  'Água Branca',

  // Amapá
  'Macapá',
  'Santana',
  'Laranjal do Jari',
  'Oiapoque',
  'Mazagão',
  'Porto Grande',
  'Tartarugalzinho',
  'Pedra Branca do Amapari',
  'Vitória do Jari',
  'Ferreira Gomes',
  'Calçoene',
  'Amapá',
  'Pracuúba',
  'Itaubal',
  'Cutias',
  'Serra do Navio',

  // Amazonas
  'Manaus',
  'Parintins',
  'Itacoatiara',
  'Manacapuru',
  'Coari',
  'Tefé',
  'Tabatinga',
  'Iranduba',
  'Humaitá',
  'Maués',
  'São Gabriel da Cachoeira',
  'Careiro',
  'Eirunepé',
  'Presidente Figueiredo',
  'Rio Preto da Eva',
  'Lábrea',
  'Manicoré',
  'Autazes',
  'Benjamin Constant',
  'Fonte Boa',
  'Boca do Acre',
  'Borba',
  'Novo Airão',
  'Carauari',
  'São Paulo de Olivença',
  'Barcelos',
  'Jutaí',
  'Tonantins',
  'Novo Aripuanã',
  'Urucará',

  // Bahia
  'Salvador',
  'Feira de Santana',
  'Vitória da Conquista',
  'Camaçari',
  'Itabuna',
  'Juazeiro',
  'Lauro de Freitas',
  'Ilhéus',
  'Jequié',
  'Teixeira de Freitas',
  'Alagoinhas',
  'Barreiras',
  'Simões Filho',
  'Paulo Afonso',
  'Eunápolis',
  'Santo Antônio de Jesus',
  'Valença',
  'Candeias',
  'Guanambi',
  'Jacobina',
  'Serrinha',
  'Senhor do Bonfim',
  'Dias d\'Ávila',
  'Brumado',
  'Porto Seguro',
  'Luís Eduardo Magalhães',
  'Irecê',
  'Conceição do Coité',
  'Itapetinga',
  'Itamaraju',
  'Castro Alves',
  'Itaberaba',
  'Cruz das Almas',
  'Ipirá',
  'Euclides da Cunha',
  'Ribeira do Pombal',
  'Catu',
  'Esplanada',
  'Tucano',
  'Bom Jesus da Lapa',
  'Santo Amaro',
  'Amargosa',
  'Cipó',
  'Camacan',
  'Valente',
  'Campo Formoso',
  'Cachoeira',
  'Itapicuru',
  'Nazaré',
  'Cícero Dantas',
  'Araci',
  'Monte Santo',
  'Capim Grosso',
  'Pojuca',
  'Madre de Deus',
  'Gandu',
  'Caetité',
  'Coaraci',
  'Ipiaú',
  'Muritiba',
  'Santa Maria da Vitória',
  'Correntina',
  'Paripiranga',
  'Cafarnaum',
  'Ruy Barbosa',
  'Mata de São João',

  // Ceará
  'Fortaleza',
  'Caucaia',
  'Juazeiro do Norte',
  'Maracanaú',
  'Sobral',
  'Crato',
  'Itapipoca',
  'Maranguape',
  'Iguatu',
  'Quixadá',
  'Canindé',
  'Pacajus',
  'Aquiraz',
  'Quixeramobim',
  'Crateús',
  'Cascavel',
  'Russas',
  'Pacatuba',
  'Icó',
  'Horizonte',
  'Aracati',
  'Camocim',
  'Morada Nova',
  'Acaraú',
  'Barbalha',
  'Limoeiro do Norte',
  'Tianguá',
  'Tauá',
  'Eusébio',
  'Beberibe',
  'Viçosa do Ceará',
  'São Gonçalo do Amarante',
  'Paracuru',
  'Jaguaruana',
  'Senador Pompeu',
  'Brejo Santo',
  'Trairi',
  'Guaraciaba do Norte',
  'Pacoti',
  'Granja',
  'Itarema',
  'Jijoca de Jericoacoara',
  'Pentecoste',
  'São Benedito',

  // Distrito Federal
  'Brasília',
  'Ceilândia',
  'Taguatinga',
  'Samambaia',
  'Planaltina',
  'Águas Claras',
  'Gama',
  'Santa Maria',
  'Recanto das Emas',
  'Vicente Pires',
  'Sobradinho',
  'Guará',
  'Brazlândia',
  'Paranoá',
  'São Sebastião',
  'Riacho Fundo',

  // Espírito Santo
  'Vitória',
  'Vila Velha',
  'Serra',
  'Cariacica',
  'Viana',
  'Guarapari',
  'Linhares',
  'Cachoeiro de Itapemirim',
  'São Mateus',
  'Colatina',
  'Aracruz',
  'Venda Nova do Imigrante',
  'Domingos Martins',
  'Nova Venécia',
  'Barra de São Francisco',
  'Itapemirim',
  'Marataízes',
  'Castelo',
  'Piúma',
  'Fundão',
  'Conceição da Barra',
  'Santa Maria de Jetibá',
  'Anchieta',
  'Afonso Cláudio',
  'Mimoso do Sul',
  'Presidente Kennedy',
  'Jaguaré',
  'Iúna',
  'Montanha',
  'São Gabriel da Palha',
  'Itarana',
  'Sooretama',
  'Ecoporanga',
  'Pinheiros',
  'Alegre',
  'Guaçuí',
  'Iconha',
  'Santa Teresa',

  // Goiás
  'Goiânia',
  'Aparecida de Goiânia',
  'Anápolis',
  'Rio Verde',
  'Luziânia',
  'Águas Lindas de Goiás',
  'Valparaíso de Goiás',
  'Trindade',
  'Formosa',
  'Novo Gama',
  'Itumbiara',
  'Senador Canedo',
  'Catalão',
  'Jataí',
  'Planaltina',
  'Caldas Novas',
  'Santo Antônio do Descoberto',
  'Goianésia',
  'Cidade Ocidental',
  'Mineiros',
  'Cristalina',
  'Inhumas',
  'Quirinópolis',
  'Porangatu',
  'Morrinhos',
  'Goiatuba',
  'Ceres',
  'Jaraguá',
  'Iporá',
  'Uruaçu',
  'Goiás',
  'Itaberaí',
  'Pirenópolis',
  'Alexânia',
  'São Luís de Montes Belos',
  'Aragarças',
  'Palmeiras de Goiás',
  'Ipameri',
  'Posse',
  'Edéia',
  'Padre Bernardo',
  'Anicuns',
  'Rubiataba',
  'Niquelândia',

  // Maranhão
  'São Luís',
  'Imperatriz',
  'São José de Ribamar',
  'Timon',
  'Caxias',
  'Codó',
  'Paço do Lumiar',
  'Açailândia',
  'Bacabal',
  'Balsas',
  'Barra do Corda',
  'Santa Inês',
  'Pinheiro',
  'Pedreiras',
  'Santa Luzia',
  'Chapadinha',
  'Grajaú',
  'Presidente Dutra',
  'Viana',
  'Itapecuru Mirim',
  'Coelho Neto',
  'Rosário',
  'Carolina',
  'Tutóia',
  'São Mateus do Maranhão',
  'Arari',
  'Colinas',
  'Vargem Grande',
  'Riachão',
  'Coroatá',
  'Lago da Pedra',
  'Peritoró',
  'Cantanhede',
  'Barreirinhas',
  'São Bento',
  'Paulo Ramos',
  'Dom Pedro',
  'Buriti',
  'Zé Doca',
  'Alcântara',

  // Mato Grosso
  'Cuiabá',
  'Várzea Grande',
  'Rondonópolis',
  'Sinop',
  'Tangará da Serra',
  'Cáceres',
  'Sorriso',
  'Lucas do Rio Verde',
  'Barra do Garças',
  'Primavera do Leste',
  'Alta Floresta',
  'Pontes e Lacerda',
  'Juína',
  'Nova Mutum',
  'Colíder',
  'Diamantino',
  'Peixoto de Azevedo',
  'Guarantã do Norte',
  'Campo Verde',
  'Mirassol d\'Oeste',
  'Água Boa',
  'Araputanga',
  'Aripuanã',
  'Juara',
  'Jaciara',
  'São José dos Quatro Marcos',
  'Confresa',
  'Poconé',
  'Matupá',
  'Paranatinga',
  'Poxoréu',
  'Vila Rica',
  'Chapada dos Guimarães',
  'Rosário Oeste',
  'Sapezal',
  'Cotriguaçu',
  'Campo Novo do Parecis',
  'Nova Xavantina',
  'Brasnorte',
  'Querência',

  // Mato Grosso do Sul
  'Campo Grande',
  'Dourados',
  'Três Lagoas',
  'Corumbá',
  'Ponta Porã',
  'Sidrolândia',
  'Aquidauana',
  'Naviraí',
  'Nova Andradina',
  'Paranaíba',
  'Coxim',
  'Maracaju',
  'São Gabriel do Oeste',
  'Amambai',
  'Rio Brilhante',
  'Jardim',
  'Caarapó',
  'Chapadão do Sul',
  'Aparecida do Taboado',
  'Itaporã',
  'Anastácio',
  'Cassilândia',
  'Miranda',
  'Ivinhema',
  'Ribas do Rio Pardo',
  'Bataguassu',
  'Eldorado',
  'Costa Rica',
  'Terenos',
  'Ladário',
  'Sonora',
  'Bela Vista',
  'Bonito',
  'Iguatemi',
  'Água Clara',
  'Rochedo',
  'Dois Irmãos do Buriti',

  // Minas Gerais
  'Belo Horizonte',
  'Uberlândia',
  'Contagem',
  'Juiz de Fora',
  'Betim',
  'Montes Claros',
  'Ribeirão das Neves',
  'Uberaba',
  'Governador Valadares',
  'Ipatinga',
  'Santa Luzia',
  'Sete Lagoas',
  'Divinópolis',
  'Ibirité',
  'Poços de Caldas',
  'Patos de Minas',
  'Teófilo Otoni',
  'Sabará',
  'Pouso Alegre',
  'Barbacena',
  'Varginha',
  'Conselheiro Lafaiete',
  'Araguari',
  'Itabira',
  'Passos',
  'Coronel Fabriciano',
  'Muriaé',
  'Nova Lima',
  'Ituiutaba',
  'Itajubá',
  'Araxá',
  'Lavras',
  'Nova Serrana',
  'Ubá',
  'Vespasiano',
  'Alfenas',
  'São João del-Rei',
  'Timóteo',
  'Formiga',
  'Cataguases',
  'Curvelo',
  'Paracatu',
  'Manhuaçu',
  'Patrocínio',
  'Ouro Preto',
  'Três Corações',
  'São Sebastião do Paraíso',
  'Pará de Minas',
  'Itaúna',
  'Viçosa',
  'João Monlevade',
  'Janaúba',
  'Leopoldina',
  'Ponte Nova',
  'Esmeraldas',
  'Frutal',
  'Lagoa Santa',
  'Caratinga',
  'Extrema',
  'Itabirito',
  'Congonhas',
  'Salinas',
  'Carangola',
  'Campos Altos',
  'Almenara',
  'Santos Dumont',
  'Januária',
  'Bom Despacho',
  'São Lourenço',
  'Além Paraíba',
  'Guaxupé',
  'Nanuque',
  'Bocaiúva',
  'Porteirinha',
  'Mariana',
  'Várzea da Palma',
  'Capelinha',
  'Ouro Branco',
  'Três Pontas',
  'Visconde do Rio Branco',
  'Campo Belo',
  'Boa Esperança',
  'Pompéu',
  'Diamantina',
  'Pirapora',
  'Monte Carmelo',
  'Coromandel',
  'Aimorés',
  'Pedro Leopoldo',
  'Andradas',
  'Mantena',
  'Machado',
  'Nepomuceno',
  'Lima Duarte',
  'Rio Pomba',

  // Pará
  'Belém',
  'Ananindeua',
  'Santarém',
  'Marabá',
  'Castanhal',
  'Parauapebas',
  'Itaituba',
  'Cametá',
  'Bragança',
  'Abaetetuba',
  'Marituba',
  'Altamira',
  'Tucuruí',
  'Barcarena',
  'Breves',
  'Benevides',
  'Capanema',
  'Paragominas',
  'Redenção',
  'Salinópolis',
  'Tailândia',
  'São Félix do Xingu',
  'Maracanã',
  'Oriximiná',
  'Vigia',
  'Tomé-Açu',
  'Igarapé-Açu',
  'Moju',
  'Soure',
  'Xinguara',
  'Viseu',
  'Medicilândia',
  'São Miguel do Guamá',
  'Conceição do Araguaia',
  'Monte Alegre',
  'Óbidos',
  'Curuçá',
  'Breu Branco',
  'Rondon do Pará',
  'Tucumã',
  'Igarapé-Miri',
  'Capitão Poço',
  'Santa Izabel do Pará',
  'Salvaterra',
  'Pacajá',
  'Acará',
  'Itupiranga',
  'Marapanim',
  'Inhangapi',
  'Jacareacanga',
  'Cachoeira do Arari',

  // Paraíba
  'João Pessoa',
  'Campina Grande',
  'Santa Rita',
  'Patos',
  'Bayeux',
  'Sousa',
  'Cajazeiras',
  'Guarabira',
  'Cabedelo',
  'Mamanguape',
  'Pombal',
  'Sapé',
  'Monteiro',
  'Itabaiana',
  'Conde',
  'Esperança',
  'Mari',
  'Princesa Isabel',
  'Caaporã',
  'Itaporanga',
  'São Bento',
  'Alhandra',
  'Pedras de Fogo',
  'Conceição',
  'Catolé do Rocha',
  'Rio Tinto',
  'Picuí',
  'Lucena',
  'Piancó',
  'Areia',
  'Cuité',
  'Queimadas',
  'Sumé',
  'São João do Rio do Peixe',
  'Alagoa Grande',
  'Bananeiras',
  'Taperoá',
  'Cruz do Espírito Santo',
  'Pitimbu',
  'Solânea',
  'Puxinanã',
  'Remígio',
  'Ingá',
  'Belém',

  // Paraná
  'Curitiba',
  'Londrina',
  'Maringá',
  'Ponta Grossa',
  'Cascavel',
  'São José dos Pinhais',
  'Foz do Iguaçu',
  'Colombo',
  'Guarapuava',
  'Paranaguá',
  'Araucária',
  'Toledo',
  'Apucarana',
  'Pinhais',
  'Campo Largo',
  'Almirante Tamandaré',
  'Umuarama',
  'Piraquara',
  'Cambé',
  'Paranavaí',
  'Francisco Beltrão',
  'Fazenda Rio Grande',
  'Sarandi',
  'Pato Branco',
  'Arapongas',
  'Telêmaco Borba',
  'Rolândia',
  'União da Vitória',
  'Irati',
  'Campo Mourão',
  'Pinhão',
  'Ivaiporã',
  'Ibiporã',
  'Dois Vizinhos',
  'Palmas',
  'Cianorte',
  'Cornélio Procópio',
  'Marechal Cândido Rondon',
  'Medianeira',
  'Santo Antônio da Platina',
  'Loanda',
  'Jacarezinho',
  'Assis Chateaubriand',
  'Matinhos',
  'Bandeirantes',
  'Castro',
  'Carambeí',
  'Lapa',
  'Antonina',
  'Quedas do Iguaçu',
  'Laranjeiras do Sul',
  'Barracão',
  'Cerro Azul',
  'Guaratuba',
  'Terra Boa',
  'Pontal do Paraná',
  'Santa Helena',
  'Guaíra',
  'Pitanga',
  'Reserva',
  'Morretes',

  // Pernambuco
  'Recife',
  'Jaboatão dos Guararapes',
  'Olinda',
  'Paulista',
  'Caruaru',
  'Petrolina',
  'Cabo de Santo Agostinho',
  'Camaragibe',
  'Garanhuns',
  'Vitória de Santo Antão',
  'Igarassu',
  'São Lourenço da Mata',
  'Abreu e Lima',
  'Santa Cruz do Capibaribe',
  'Ipojuca',
  'Serra Talhada',
  'Araripina',
  'Gravatá',
  'Carpina',
  'Goiana',
  'Belo Jardim',
  'Arcoverde',
  'Ouricuri',
  'Escada',
  'Pesqueira',
  'Surubim',
  'Palmares',
  'Bezerros',
  'Salgueiro',
  'São Bento do Una',
  'Limoeiro',
  'Paudalho',
  'Timbaúba',
  'Moreno',
  'Ribeirão',
  'Rio Formoso',
  'Barreiros',
  'Sirinhaém',
  'Buíque',
  'Afogados da Ingazeira',
  'Nazaré da Mata',
  'Toritama',
  'Águas Belas',
  'Triunfo',
  'Lagoa do Itaenga',
  'Tamandaré',
  'Bonito',
  'Lagoa Grande',
  'Itamaracá',
  'Itapissuma',
  'João Alfredo',
  'Ferreiros',

  // Piauí
  'Teresina',
  'Parnaíba',
  'Picos',
  'Piripiri',
  'Floriano',
  'Campo Maior',
  'Barras',
  'União',
  'Altos',
  'Esperantina',
  'Pedro II',
  'Valença do Piauí',
  'São Raimundo Nonato',
  'Oeiras',
  'Luís Correia',
  'Piracuruca',
  'Canto do Buriti',
  'Amarante',
  'Jaicós',
  'Paulistana',
  'Simplício Mendes',
  'Bom Jesus',
  'Cocal',
  'São João do Piauí',
  'Inhuma',
  'Miguel Alves',
  'Demerval Lobão',
  'Castelo do Piauí',
  'Corrente',
  'Buriti dos Lopes',
  'José de Freitas',
  'Fronteiras',
  'Regeneração',
  'Uruçuí',
  'Joaquim Pires',
  'Gilbués',
  'Água Branca',
  'Luzilândia',
  'Beneditinos',
  'Capitão de Campos',
  'Batalha',
  'Elesbão Veloso',

  // Rio de Janeiro
  'Rio de Janeiro',
  'São Gonçalo',
  'Duque de Caxias',
  'Nova Iguaçu',
  'Niterói',
  'Belford Roxo',
  'Campos dos Goytacazes',
  'São João de Meriti',
  'Petrópolis',
  'Volta Redonda',
  'Magé',
  'Itaboraí',
  'Macaé',
  'Cabo Frio',
  'Nova Friburgo',
  'Barra Mansa',
  'Angra dos Reis',
  'Mesquita',
  'Teresópolis',
  'Nilópolis',
  'Maricá',
  'Queimados',
  'Rio das Ostras',
  'Resende',
  'Araruama',
  'Itaguaí',
  'Japeri',
  'Itaperuna',
  'São Pedro da Aldeia',
  'Barra do Piraí',
  'Seropédica',
  'Saquarema',
  'Três Rios',
  'Valença',
  'Rio Bonito',
  'Guapimirim',
  'Cachoeiras de Macacu',
  'Paracambi',
  'Paraíba do Sul',
  'Itatiaia',
  'São Francisco de Itabapoana',
  'Santo Antônio de Pádua',
  'Arraial do Cabo',
  'Silva Jardim',
  'São Fidélis',
  'Casimiro de Abreu',
  'Tanguá',
  'Iguaba Grande',
  'Bom Jardim',
  'Cambuci',
  'Mangaratiba',
  'Vassouras',
  'Piraí',
  'Pinheiral',
  'Parati',
  'Itaocara',
  'Sapucaia',
  'Miguel Pereira',
  'Cordeiro',
  'Conceição de Macabu',
  'Quissamã',
  'Carapebus',
  'Paty do Alferes',
  'Porto Real',
  'São José do Vale do Rio Preto',

  // Rio Grande do Norte
  'Natal',
  'Mossoró',
  'Parnamirim',
  'São Gonçalo do Amarante',
  'Macaíba',
  'Ceará-Mirim',
  'Caicó',
  'Assu',
  'Currais Novos',
  'São José de Mipibu',
  'Nova Cruz',
  'Apodi',
  'Santa Cruz',
  'João Câmara',
  'Pau dos Ferros',
  'Extremoz',
  'Touros',
  'Goianinha',
  'Areia Branca',
  'Nísia Floresta',
  'São Paulo do Potengi',
  'Macau',
  'Canguaretama',
  'Monte Alegre',
  'Baraúna',
  'Caraúbas',
  'Guamaré',
  'Angicos',
  'Jardim do Seridó',
  'Alexandria',
  'Jucurutu',
  'Pedro Avelino',
  'Parelhas',
  'Acari',
  'Vera Cruz',
  'São Miguel',
  'Upanema',
  'Pendências',
  'Carnaubais',
  'Taipu',
  'Lajes',
  'Brejinho',
  'Grossos',
  'Santo Antônio',
  'Lagoa Nova',
  'Tibau',

  // Rio Grande do Sul
  'Porto Alegre',
  'Caxias do Sul',
  'Pelotas',
  'Canoas',
  'Santa Maria',
  'Gravataí',
  'Viamão',
  'Novo Hamburgo',
  'São Leopoldo',
  'Rio Grande',
  'Alvorada',
  'Passo Fundo',
  'Sapucaia do Sul',
  'Uruguaiana',
  'Santa Cruz do Sul',
  'Cachoeirinha',
  'Bagé',
  'Bento Gonçalves',
  'Erechim',
  'Guaíba',
  'Santana do Livramento',
  'Lajeado',
  'Cachoeira do Sul',
  'Esteio',
  'Ijuí',
  'Alegrete',
  'Sapiranga',
  'Santo Ângelo',
  'São Borja',
  'Farroupilha',
  'Camaquã',
  'Venâncio Aires',
  'Cruz Alta',
  'Montenegro',
  'São Gabriel',
  'Vacaria',
  'Campo Bom',
  'Carazinho',
  'Tramandaí',
  'Parobé',
  'Novo Prado',
  'Taquara',
  'Santiago',
  'Itaqui',
  'São Lourenço do Sul',
  'Teutônia',
  'Capão da Canoa',
  'Rosário do Sul',
  'Três Passos',
  'Estância Velha',
  'Osório',
  'Igrejinha',
  'Frederico Westphalen',
  'Santa Rosa',
  'Charqueadas',
  'Encantado',
  'Arroio Grande',
  'Estrela',
  'Soledade',
  'Portão',
  'Marau',
  'Horizontina',
  'Palmeira das Missões',
  'Torres',
  'Júlio de Castilhos',
  'Dom Pedrito',
  'Tupanciretã',
  'São Jerônimo',
  'Canela',
  'Giruá',
  'Quaraí',
  'Triunfo',
  'Três Coroas',
  'Gramado',
  'Dois Irmãos',
  'Eldorado do Sul',
  'Arroio do Meio',
  'Serafina Corrêa',
  'Camargo',
  'São Marcos',
  'Ivoti',
  'Mostardas',
  'Nova Prata',
  'Lagoa Vermelha',
  'Butiá',

  // Rondônia
  'Porto Velho',
  'Ji-Paraná',
  'Ariquemes',
  'Vilhena',
  'Cacoal',
  'Jaru',
  'Rolim de Moura',
  'Guajará-Mirim',
  'Buritis',
  'Ouro Preto do Oeste',
  'Pimenta Bueno',
  'Presidente Médici',
  'Espigão d\'Oeste',
  'Colorado do Oeste',
  'Cerejeiras',
  'São Miguel do Guaporé',
  'Nova Brasilândia d\'Oeste',
  'Machadinho d\'Oeste',
  'Candeias do Jamari',
  'Alvorada d\'Oeste',
  'Alta Floresta d\'Oeste',
  'Costa Marques',
  'Nova Mamoré',
  'Campo Novo de Rondônia',
  'Monte Negro',
  'Cujubim',
  'Governador Jorge Teixeira',
  'Itapuã do Oeste',

  // Roraima
  'Boa Vista',
  'Rorainópolis',
  'Caracaraí',
  'Alto Alegre',
  'Mucajaí',
  'São João da Baliza',
  'São Luiz',
  'Bonfim',
  'Cantá',
  'Normandia',
  'Pacaraima',
  'Caroebe',
  'Iracema',
  'Amajari',
  'Uiramutã',

  // Santa Catarina
  'Florianópolis',
  'Joinville',
  'Blumenau',
  'São José',
  'Criciúma',
  'Chapecó',
  'Itajaí',
  'Jaraguá do Sul',
  'Lages',
  'Palhoça',
  'Balneário Camboriú',
  'Brusque',
  'Tubarão',
  'São Bento do Sul',
  'Caçador',
  'Concórdia',
  'Camboriú',
  'Navegantes',
  'Rio do Sul',
  'Araranguá',
  'Gaspar',
  'Biguaçu',
  'Indaial',
  'Itapema',
  'Mafra',
  'Canoinhas',
  'Içara',
  'Videira',
  'Tijucas',
  'Araquari',
  'Joaçaba',
  'Imbituba',
  'São Francisco do Sul',
  'Sombrio',
  'Xanxerê',
  'Curitibanos',
  'Balneário Piçarras',
  'Braço do Norte',
  'Santo Amaro da Imperatriz',
  'Lauro Müller',
  'Guaramirim',
  'São Ludgero',
  'Maravilha',
  'Penha',
  'Porto Belo',
  'Laguna',
  'Orleans',
  'Urussanga',
  'Campos Novos',
  'Timbó',
  'Tangará',
  'Criciúma',
  'São Miguel do Oeste',
  'Fraiburgo',
  'Pomerode',
  'Ibirama',
  'Schroeder',
  'Capivari de Baixo',
  'Massaranduba',
  'Içara',
  'Tubarão',
  'Bombinhas',
  'Garopaba',
  'São Joaquim',
  'Treze Tílias',
  'Águas Mornas',

  // São Paulo
  'São Paulo',
  'Guarulhos',
  'Campinas',
  'São Bernardo do Campo',
  'Santo André',
  'Osasco',
  'São José dos Campos',
  'Ribeirão Preto',
  'Sorocaba',
  'Mauá',
  'São José do Rio Preto',
  'Mogi das Cruzes',
  'Santos',
  'Diadema',
  'Jundiaí',
  'Carapicuíba',
  'Piracicaba',
  'Bauru',
  'Itaquaquecetuba',
  'São Vicente',
  'Franca',
  'Guarujá',
  'Taubaté',
  'Praia Grande',
  'Limeira',
  'Suzano',
  'Taboão da Serra',
  'Sumaré',
  'Barueri',
  'Embu das Artes',
  'São Carlos',
  'Marília',
  'Indaiatuba',
  'Cotia',
  'Americana',
  'Jacareí',
  'Araraquara',
  'Presidente Prudente',
  'Rio Claro',
  'Araçatuba',
  'Santa Bárbara d\'Oeste',
  'Hortolândia',
  'Itapevi',
  'Ferraz de Vasconcelos',
  'Francisco Morato',
  'São Caetano do Sul',
  'Itapecerica da Serra',
  'Itu',
  'Bragança Paulista',
  'Pindamonhangaba',
  'Várzea Paulista',
  'Caraguatatuba',
  'Botucatu',
  'Jaboticabal',
  'Atibaia',
  'Araras',
  'Cubatão',
  'Ribeirão Pires',
  'Santana de Parnaíba',
  'Sertãozinho',
  'Catanduva',
  'Barretos',
  'Guaratinguetá',
  'Jandira',
  'Mogi Guaçu',
  'Salto',
  'Birigui',
  'Itapetininga',
  'Tatuí',
  'Ourinhos',
  'São João da Boa Vista',
  'Assis',
  'Votorantim',
  'Valinhos',
  'Itanhaém',
  'Praia Grande',
  'Cajamar',
  'Itapeva',
  'Leme',
  'Cruzeiro',
  'Lorena',
  'Vinhedo',
  'Franco da Rocha',
  'Itatiba',
  'São Roque',
  'Jaú',
  'Caçapava',
  'Matão',
  'Itapira',
  'Mococa',
  'Registro',
  'Bebedouro',
  'Votuporanga',
  'Olímpia',
  'Itapeví',
  'Igarapava',
  'Lins',
  'Tupã',
  'São José do Rio Pardo',
  'Taquaritinga',
  'Fernandópolis',
  'Pirassununga',
  'Itupeva',
  'Campo Limpo Paulista',
  'Mongaguá',
  'Mogi Mirim',
  'Cerquilho',
  'Piedade',
  'Paraguaçu Paulista',
  'São Sebastião',
  'Andradina',
  'Penápolis',
  'Jales',
  'Aparecida',
  'Amparo',
  'Porto Feliz',
  'Tanabi',
  'Ibiúna',
  'Cosmópolis',
  'Pederneiras',
  'Charqueada',

  // Sergipe
  'Aracaju',
  'Nossa Senhora do Socorro',
  'Lagarto',
  'Itabaiana',
  'Estância',
  'São Cristóvão',
  'Tobias Barreto',
  'Simão Dias',
  'Propriá',
  'Barra dos Coqueiros',
  'Laranjeiras',
  'Umbaúba',
  'Maruim',
  'Poço Verde',
  'Capela',
  'Aquidabã',
  'Itabaianinha',
  'Boquim',
  'Ribeirópolis',
  'Carmópolis',
  'Canindé de São Francisco',
  'Neópolis',
  'Arauá',
  'Campo do Brito',
  'Frei Paulo',
  'Japaratuba',
  'Porto da Folha',
  'Gararu',
  'Carira',
  'Rosário do Catete',
  'São Domingos',
  'Moita Bonita',
  'Riachuelo',
  'Santa Luzia do Itanhy',
  'Cristinápolis',

  // Tocantins
  'Palmas',
  'Araguaína',
  'Gurupi',
  'Porto Nacional',
  'Paraíso do Tocantins',
  'Colinas do Tocantins',
  'Guaraí',
  'Tocantinópolis',
  'Miracema do Tocantins',
  'Araguatins',
  'Formoso do Araguaia',
  'Dianópolis',
  'Arraias',
  'Pedro Afonso',
  'Augustinópolis',
  'Xambioá',
  'Alvorada',
  'Gurupi',
  'Axixá do Tocantins',
  'Taguatinga',
  'Wanderlândia',
  'Goiatins',
  'Miranorte',
  'Araguaçu',
  'Nova Olinda',
  'Peixe',
  'Porto Alegre do Tocantins',
  'Palmeirópolis',
  'Ananás',
  'Paraná',
  'Babaçulândia',
  'Filadélfia',
  'Campos Lindos',
].sort();
